### ISSUE TITLE
Issue with css

### ISSUE THREAD

**Issue by srikanth748** [flatlogic/angular-dashboard-seed#21]
I cloned the project and did exactly what is said in the Readme .But when serve the project the css doesnt load .When I tried to inspect the index.html , the css file name is index.css ,but the file name is not the same as it as scss as extnsn( index.scss).and the other thing I noted is that in the
 index.css 
@import "theme/navigation";
@import "theme/layout";
@import "theme/login";
@import "theme/override-bootstrap";
@import "theme/dashboard";
@import "theme/validation";
@import "theme/utils";
but the file names are different because they have an underscore before them like (theme/_navigation)

I am looking for help if somebody could make me understand why my css files are not loading .Thnx

**Comment by DimaSavchenko** [comment]
Hi @srikanth748 ! 
For running project you should follow these steps:

1) git clone https://github.com/flatlogic/angular-dashboard-seed.git
2) npm install && bower install
3) gulp serve
4) go to http://localhost:3000
5) Enter username: user1, password: user1pass

**Comment by Veerbhadra277** [comment]
followed all steps but css is not getting loaded, when I tried to build code using 'gulp build' it gives me following error,

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ENOENT: no such file or directory, open 'D:\Veer\angular-dashboard-seed\{D:\Veer\angular-dashboard-seed\.tmp\app\index.css,D:\Veer\angular-dashboard-seed\src\app\index.css}'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at DestroyableTransform.<anonymous> (D:\Veer\angular-dashboard-seed\node_modules\gulp-useref\index.js:81:61)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (D:\Veer\angular-dashboard-seed\node_modules\gulp-useref\index.js:70:35)
    at Array.forEach (native)
    at DestroyableTransform.<anonymous> (D:\Veer\angular-dashboard-seed\node_modules\gulp-useref\index.js:46:36)
    at Array.forEach (native)
    at DestroyableTransform._transform (D:\Veer\angular-dashboard-seed\node_modules\gulp-useref\index.js:43:15)

Thanks in advance for help

Regards,
Veer

**Comment by Veerbhadra277** [comment]
Fixed issue by following steps,
1. Install Rubby
2. run following cmnd in proj folder
sass - -watch main.scss:main.css (enter)
